### ISSUE TITLE
Feature ExpressLRS v.2 support

### ISSUE THREAD

**Issue by Noramas** [BETAFPV/LiteRadio_PLUS#2]
Please add ExpressLRS V.2.0.0 support to LiteRadio SE2 and SE3

**Comment by HWT662988** [comment]
I'm working on it.

**Comment by HWT662988** [comment]
Here is the  firmware of ELRS V.2.0.0 support for  LiteRadio SE V2:
[LiteRadio_2_SE_V2_SX1280_2.0.0_RC1.zip](https://github.com/BETAFPV/LiteRadio_PLUS/files/7827204/LiteRadio_2_SE_V2_SX1280_2.0.0_RC1.zip)

you can test if it is available.

**Comment by HWT662988** [comment]
It can be flashed and tested in LiteRadio V3 also,But only  the internal RF module could be selected.

**Comment by kingjamez** [comment]
Got ELRS V2.0 installed on my LiteRadio2 SE. How do we update our BetaFPV ELRS AIO boards to V2.0?

**Comment by Noramas** [comment]
Update Betaflight to 4.3. Use appropriate target for your board- probably BETAFPVSX1280

**Comment by HWT662988** [comment]
Here is the latest  firmware of ELRS V.2.0.0 support for LiteRadio SE V2 and LiteRadio V3: https://github.com/BETAFPV/LiteRadio_PLUS/releases/tag/v2.0.0
