### ISSUE TITLE
Lite Radio 3: Disable sounds

### ISSUE THREAD

**Issue by stylesuxx** [BETAFPV/LiteRadio_PLUS#3]
I would really like to see an option to disable the sounds - I find them a bit annoying.

**Comment by HWT662988** [comment]
The sound only alarms when the battery voltage is low. you  can fill it up and it won't make any more noise. which board version are you using？CC2500 or SX1280? I can compile a firmware for you that disables the buzzer under voltage alarm.

**Comment by stylesuxx** [comment]
I was talking about the sound when switchin on or turning off the radio - the low battery alarm makes sense of course. Don't waste your time with just compiling a version for me - I thought if other people feel like I do, an option in the configurator would make sense.

**Comment by HWT662988** [comment]
OK, I'll add more options on the configurator to do it in a later version If somebody have the similar ideas else.
