### ISSUE TITLE
Use LiteRadio as a Bluetooth joystick

### ISSUE THREAD

**Issue by Shpek** [BETAFPV/LiteRadio_PLUS#4]
Hi. ELRS 2.0 firmware supports connecting the radio via Bluetooth to a computer and using the radio wirelessly as a gamepad for simulators. Is it possible the LiteRadio with ELRS to be used in such a manner (connect to PC via Bluetooth as a wireless gamepad)? Is it just a matter of software or there is some kind of hardware limitation?

**Comment by liyouluo** [comment]
This firmware does not support turning on Bluetooth, because the MCU of the remote control does not use the ESP series chip.
